# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [1]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [2]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [4]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])
arr

array([23, 42, 13,  7,  0])

In [5]:
# Інспектування массива
np.info(arr)

class:  ndarray
shape:  (5,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x1781a811a90
byteorder:  little
byteswap:  False
type: int32


In [6]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [8]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [9]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

[[0.26681183 0.22215993 0.36323994]
 [0.244991   0.42355796 0.69741881]
 [0.52965427 0.25698263 0.16621683]]


In [10]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[123 123 123]
 [123 123 123]]


In [11]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

[[0.26681183 0.22215993 0.36323994]
 [0.244991   0.42355796 0.69741881]
 [0.52965427 0.25698263 0.16621683]]
...
float64
(3, 3)
3
2
9
8
72


In [12]:
arr.__sizeof__()

192

### ЗАВДАННЯ 1

In [13]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 
arr1_1 = np.array([[1, 2.2, 3, 4.5],[5, 6, 7, 8.3],[9, 10, 11.4, 12]])
print(arr1_1)

[[ 1.   2.2  3.   4.5]
 [ 5.   6.   7.   8.3]
 [ 9.  10.  11.4 12. ]]


In [14]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів
arr1_2 = np.array(["Hi","I am","a student","of","Data science faculty"])
print(arr1_2)

['Hi' 'I am' 'a student' 'of' 'Data science faculty']


In [16]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою
arr1_3 = np.ones((3,4), dtype=float)
print(arr1_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [17]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32


In [19]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float64


In [20]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### ЗАВДАННЯ 2

In [22]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'
arr2_1 = np.zeros((3,1,3), dtype=bool)
...
print(arr2_1)

[[[False False False]]

 [[False False False]]

 [[False False False]]]


In [25]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 = arr2_1.reshape((3,3))
arr2_2= arr2_2.astype("int16")
print(arr2_2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [29]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
arr2_3 = np.arange(10,21,2)
arr2_3=arr2_3.reshape(2,3)

...
print(arr2_3)

[[10 12 14]
 [16 18 20]]


## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [33]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

[10  6  7 21 44]
10
7
44


In [47]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[44 18 18 49]
 [10 26 21 11]
 [23 29 38 20]
 [29 11 35 12]]


In [48]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, -1]
print(el)

11


In [31]:
# отримати значення останнього рядка
vect = arr[-1]
print(vect)

[20 31 20 39]


In [34]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

[10  6]


In [56]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

[[18 18]
 [26 21]
 [29 38]
 [11 35]]


In [37]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

[10  7]


In [38]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

[21 44]


### ЗАВДАННЯ 3

In [39]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
arr3_1 = np.random.randint(10, 100, (4,5))
arr3_1

array([[74, 46, 86, 90, 36],
       [81, 51, 64, 61, 33],
       [87, 87, 33, 96, 53],
       [72, 41, 24, 25, 96]])

In [50]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
el3_2 = arr3_1[2, 2]
print(el3_2)

33


In [55]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
vect3_3 = arr3_1[1:2]
print(vect3_3)

[[81 51 64 61 33]]


In [66]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
vect3_4 = arr3_1[0:4, 2:3]
print(vect3_4)

[[86]
 [64]
 [33]
 [24]]


In [95]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`
a=arr3_1[1:2, 0:-1]
b= arr3_1[2:3, 0:-1]
c= arr3_1[0:4, 1:2].T
v= arr3_1[0:4, 2:3].T
mat3_5 = np.array([[a],[b],[c],[v]])


print(mat3_5)


[[[[81 51 64 61]]]


 [[[87 87 33 96]]]


 [[[46 51 87 41]]]


 [[[86 64 33 24]]]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [96]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [159]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [160]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

[[0.33993231 0.10172988 0.69276231 0.01415896 0.5817481 ]
 [0.68314795 0.48344831 0.59055779 0.36568211 0.61443474]
 [0.42090105 0.08529643 0.36023922 0.33473139 0.91680764]
 [0.05952998 0.50967368 0.69599155 0.42492183 0.08024669]
 [0.45816941 0.08865954 0.87286652 0.12346418 0.41049844]]
...
[0.33993231 0.48344831 0.36023922 0.42492183 0.41049844]


In [99]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

[[3.72611785e-01 5.97363990e-01 5.34577767e-02 5.49459005e-02
  1.22853980e-01]
 [3.36813552e-01 8.45613608e-01 9.39257332e-01 3.63477887e-02
  1.48065782e-01]
 [1.65381585e-01 5.14216692e-01 7.49505997e-01 6.93611459e-01
  3.22097214e-01]
 [6.73730285e-01 6.14923373e-01 8.72123656e-04 7.57001651e-01
  9.91827567e-01]
 [5.02627425e-01 9.63651818e-01 6.14410017e-02 4.82868069e-01
  3.81082278e-01]]


In [100]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

-0.02699289236466862


In [101]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

[[13.8629764  -5.6553144   1.32980506  3.40093711 -8.50752396]
 [-3.50106972  1.73701776  0.36737569 -2.25241956  3.0200903 ]
 [ 4.05870763 -2.14608916  0.92076842  2.68419798 -3.47594612]
 [ 0.58426185 -0.61193747  0.14678023 -0.47132843  1.3503639 ]
 [-8.05998808  4.55484519 -1.73171325 -1.26326671  3.61674012]]


### ЗАВАДАННЯ 4

In [102]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200
mat4_1 = np.random.rand(100,200)
print(mat4_1)

[[0.51552441 0.35991248 0.04634742 ... 0.68092536 0.50557061 0.08440746]
 [0.83263323 0.24286286 0.89299663 ... 0.66728052 0.68106035 0.75825933]
 [0.33575255 0.54662179 0.20192745 ... 0.40033899 0.90751719 0.69427351]
 ...
 [0.89144347 0.05702931 0.89717364 ... 0.96552854 0.25281268 0.6982235 ]
 [0.4389387  0.38003208 0.55947337 ... 0.89361529 0.8207328  0.15316637]
 [0.04669249 0.65755775 0.27417135 ... 0.79972282 0.47368899 0.0348615 ]]


In [104]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
diag4_2 = np.diag(mat4_1)
print(diag4_2)

[0.51552441 0.24286286 0.20192745 0.11638418 0.2963206  0.25632618
 0.32764963 0.90595239 0.4006488  0.3583771  0.69084707 0.30099474
 0.58806664 0.91373279 0.12379038 0.67381234 0.47155741 0.96585065
 0.18539594 0.99927999 0.125996   0.5077715  0.17780113 0.2702882
 0.24703304 0.77174751 0.71772062 0.60397346 0.92934926 0.66825614
 0.54329711 0.63803301 0.25498387 0.64159855 0.09870087 0.78711524
 0.93387545 0.35226231 0.10639589 0.8288894  0.30603132 0.64606298
 0.40219839 0.82180999 0.66795791 0.37090604 0.17283894 0.37496346
 0.60487782 0.24476569 0.65645598 0.72046835 0.90063887 0.99020123
 0.54398592 0.08624322 0.54917379 0.88595867 0.44223564 0.02298453
 0.23110815 0.63752191 0.19868383 0.55833308 0.16192738 0.9928179
 0.19430361 0.34096625 0.93836098 0.58836206 0.64296688 0.00438175
 0.75234214 0.21837337 0.41722228 0.3689019  0.89410759 0.86954563
 0.71994078 0.95279634 0.58757849 0.01803992 0.4456152  0.78815472
 0.64683631 0.36936823 0.55251351 0.35591499 0.5212191  0.327158

In [105]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'
trans4_3 = mat4_1.T
print(trans4_3)

[[0.51552441 0.83263323 0.33575255 ... 0.89144347 0.4389387  0.04669249]
 [0.35991248 0.24286286 0.54662179 ... 0.05702931 0.38003208 0.65755775]
 [0.04634742 0.89299663 0.20192745 ... 0.89717364 0.55947337 0.27417135]
 ...
 [0.68092536 0.66728052 0.40033899 ... 0.96552854 0.89361529 0.79972282]
 [0.50557061 0.68106035 0.90751719 ... 0.25281268 0.8207328  0.47368899]
 [0.08440746 0.75825933 0.69427351 ... 0.6982235  0.15316637 0.0348615 ]]


In [111]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 = np.linalg.inv(mat4_1)
print(inv4_4)

LinAlgError: Last 2 dimensions of the array must be square

## 5. Операції над масивами

### ПРИКЛАДИ

In [ ]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])

In [112]:
# вирахувати суму елеметнів
s = np.sum(vect)

# знайти мінімальний ел-т
m = np.min(vect)

# відсортувати вектор по зростанню
vs = np.sort(vect)

# знайти середнє значення
mid = np.average(vect)
...

Ellipsis

In [ ]:
# матриця 3х3 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

In [ ]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

In [ ]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

In [ ]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

In [ ]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

In [ ]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

In [ ]:
# поелементний поділ
K = N / M
print(K)

In [ ]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

In [ ]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

In [ ]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

In [ ]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

In [ ]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

In [ ]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

In [ ]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

### ЗАВДАННЯ 5

In [130]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = np.random.randint(1,12, (3,4))
sum_mat5_1 = np.sum(mat5_1, axis=0)
print(sum_mat5_1)


[13 13 17 21]


In [131]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_mat5_1 =np.min(sum_mat5_1)
print(min_mat5_1)

13


In [132]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_3 = np.array( mat5_1+100)
print(mat5_3)

[[105 101 106 106]
 [103 102 105 104]
 [105 110 106 111]]


In [177]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
v=np.diag(mat5_3)
a=np.diag([v])

mat5_4 = np.multiply(mat5_3,a)
print(mat5_4)


[[11025 10605 11130 11130]
 [10815 10710 11025 10920]
 [11025 11550 11130 11655]]


In [179]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
mat5_5 = np.concatenate(mat5_4, mat5_3)
print(np.linang.det(mat5_5))
...

TypeError: only integer scalar arrays can be converted to a scalar index